<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.1" />
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Flurl" Version="4.0.0" />
		<PackageReference Include="Flurl.Http" Version="4.0.2" />
		<PackageReference Include="log4net" Version="2.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
		<PackageReference Include="Tencent.QCloud.Cos.Sdk" Version="5.4.24" />
		<PackageReference Include="TencentCloudSDK" Version="3.0.388" />
		<PackageReference Include="SqlSugarCore" Version="5.1.4.214" />
		<PackageReference Include="MongoDB.Driver" Version="3.9.0" />
		<PackageReference Include="StackExchange.Redis" Version="3.0.0" />
		<PackageReference Include="SqlSugar.IOC" Version="2.0.1" />
	</ItemGroup>

</Project>
