<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
		<PackageReference Include="Castle.Core" Version="4.4.1" />
		<PackageReference Include="Com.Ctrip.Framework.Apollo" Version="2.11.0" />
		<PackageReference Include="Com.Ctrip.Framework.Apollo.Configuration" Version="2.11.0" />
		<PackageReference Include="Consul" Version="1.6.10.3" />
		<PackageReference Include="DotNetCore.CAP.MySql" Version="10.0.1" />
		<PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="10.0.1" />
		<PackageReference Include="Polly" Version="7.2.2" />
		<PackageReference Include="InitQ" Version="1.0.0.7" />
		<PackageReference Include="log4net" Version="2.0.12" />
		<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />
		<PackageReference Include="MiniProfiler.Shared" Version="4.5.4" />
		<PackageReference Include="NEST" Version="7.17.4" />
		<PackageReference Include="Quartz" Version="3.3.2" />
		<PackageReference Include="StackExchange.Redis" Version="3.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
		<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TBlog.Service\TBlog.Service.csproj" />
	</ItemGroup>

</Project>
